### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by scriptsure** [GrahamMThomas/apidoc_to_openapi#3]
@GrahamMThomas hey man having issues getting this installed on macos:

` pip install apidoc-to-openapi
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Collecting apidoc-to-openapi

  ERROR: Could not find a version that satisfies the requirement apidoc-to-openapi (from versions: none)
ERROR: No matching distribution found for apidoc-to-openapi

WARNING: You are using pip version 19.2.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

i do have python3 installed on 3.8..

Any ideas?

**Comment by GrahamMThomas** [comment]
Yeah so this package requires 3.6. 

You're running python2 pip. 

Try:

`pip3 install apidoc-to-openapi`
